version: "3.8"

services:
  dockerpractice:
    build: ./ops-tools/docker/images/app/
    command: java -jar ./target/docker-practice-java-0.0.1-SNAPSHOT.jar
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school
    ports:
      - 8080:8080
    networks:
      - docker-practice-net
    volumes:
      - .DockerPracticeJavaApplication/:/usr/src/DockerPracticeJavaApplication

networks:
  docker-practice-net:

