version: "3.8"

services:
  dockerpractice:
    build: .
    command: java -jar docker-practice-java-0.0.1-SNAPSHOT.class
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school
    ports:
      - 8080:8080
    networks:
      - docker-practice-net
    volumes:
      - .:/priject

networks:
  docker-practice-net:

