version: "3.8"

services:
  Postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
      - ./data/dump:/db-dump
    networks:
      - docker-practice-net

  Redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - docker-practice-net

networks:
  docker-practice-net:

